"""Add user relationship to Reservation

Revision ID: 2e0081d48b3f
Revises: 9c789dd36fbb
Create Date: 2024-11-19 12:54:54.851891

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0081d48b3f'
down_revision = '9c789dd36fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_reservation_user_id_user', 'user', ['user_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_reservation_user_id_user', type_='foreignkey'
        )
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
